export type BackupErrorCode =
  | "INVALID_JSON"
  | "VERSION_EXPECTED"
  | "MISSING_TRANSACTIONS"
  | "BAD_TRANSACTION_ROW"
  | "SETTINGS_NOT_OBJECT"
  | "TEMPLATES_NOT_ARRAY"
  | "BAD_TEMPLATE_ROW";
